server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://resource-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

